"""Lista curada de 1024 palabras en español para generación de frases de paso (Diceware).

Copyright (C) 2026 Custos
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

WORDS: tuple[str, ...] = (
    "abaco", "abeja", "abeto", "abono", "abril", "abuelo", "acacia", "aceite",
    "acento", "acero", "acierto", "actor", "adagio", "adorno", "aduana", "adulto",
    "afable", "afecto", "agenda", "agosto", "aguila", "aguja", "ahorro", "aire",
    "aislado", "ajedrez", "alarma", "album", "alcance", "aldea", "alegre", "alerta",
    "aleta", "alfombra", "alga", "aliado", "aliento", "alivio", "alma", "almena",
    "almohada", "alondra", "alpaca", "altar", "alteza", "altura", "alumno", "amable",
    "amante", "amapola", "ambar", "ambiente", "amigo", "amistad", "amparo", "ancho",
    "ancla", "andanza", "anillo", "animo", "anoche", "antena", "antorcha", "anual",
    "anuncio", "anzuelo", "aparato", "aplauso", "apogeo", "aporte", "apoyo", "aprisa",
    "arbol", "archivo", "ardilla", "arena", "arete", "aroma", "arpa", "arrecife",
    "arreglo", "arroz", "arte", "asfalto", "asiento", "asombro", "astro", "astuto",
    "atajo", "atento", "atleta", "audaz", "aurora", "avance", "avellana", "avena",
    "avion", "aviso", "avispa", "azahar", "azafran", "azteca", "azucar", "azulejo",
    "bahia", "baile", "bajada", "balanza", "balcon", "balsa", "bambu", "bandada",
    "bandera", "banquete", "barba", "barco", "barniz", "baron", "barril", "barro",
    "base", "bastidor", "batalla", "bateria", "baul", "bebe", "belleza", "bellota",
    "bengala", "beso", "bien", "bigote", "billete", "binario", "bioma", "bisonte",
    "blanco", "blindaje", "bloque", "blusa", "bobina", "boceto", "bodega", "bohemio",
    "boina", "bolero", "bolsa", "bomba", "bondad", "bonito", "boreal", "bosque",
    "botella", "boton", "boveda", "bozal", "brazo", "bravura", "brecha", "briza",
    "brisa", "broche", "bronce", "brote", "brujula", "bruma", "bueno", "bufanda",
    "buho", "buque", "burbuja", "burgues", "butaca", "buzon", "caballo", "cabana",
    "cabeza", "cable", "cacao", "cadena", "cadencia", "cadete", "caida", "caiman",
    "caja", "calambre", "calavera", "calcio", "calculo", "caldera", "caldo", "caleta",
    "calibre", "calidez", "calle", "calma", "calor", "calzado", "cambio", "camello",
    "camino", "campana", "campo", "canal", "canario", "cancion", "candil", "canguro",
    "canica", "canela", "canoa", "cantera", "cantor", "canamo", "caoba", "capa",
    "capataz", "capaz", "capilla", "capital", "capitel", "capsula", "capricho", "captura",
    "capullo", "cara", "caracol", "caramelo", "carbon", "carcaj", "careta", "carga",
    "caricia", "caridad", "carioca", "carmesi", "carnaval", "carpeta", "carretera", "carro",
    "carta", "cartel", "cascada", "casco", "caseta", "castillo", "castor", "catarata",
    "catedral", "caucho", "caudal", "causa", "caverna", "caviar", "cazador", "cebolla",
    "cedro", "celeste", "celda", "cemento", "ceniza", "cenit", "centro", "cepillo",
    "cera", "cerca", "cereza", "cerro", "certeza", "cesped", "chacal", "chaleco",
    "champa", "chapa", "charco", "charol", "chasis", "cheque", "chimenea", "chispa",
    "choza", "ciclismo", "ciclon", "ciego", "cielo", "cien", "cifra", "cigarra",
    "cima", "cimiento", "cincel", "cinco", "cine", "cinta", "cintura", "cipres",
    "circo", "circulo", "ciruela", "cisne", "cita", "ciudad", "civismo", "clara",
    "claridad", "clavel", "clavo", "cliente", "clima", "clinica", "coala", "cobre",
    "cocina", "coco", "codigo", "cofrade", "cohete", "cojin", "colchonc", "colegio",
    "colibri", "colina", "collar", "colmena", "colonia", "color", "columna", "comarca",
    "combate", "cometa", "comida", "compacto", "compas", "complejo", "compra", "comun",
    "conde", "condor", "conejo", "confort", "conjunto", "consejo", "consuelo", "contacto",
    "copa", "coral", "coraza", "corbata", "cordel", "cordero", "cordon", "cornet",
    "cornisa", "corona", "correo", "corredor", "corteza", "cortina", "cosecha", "cosmos",
    "costa", "costura", "cotidiano", "crater", "creacion", "creativo", "crema", "cresta",
    "crimen", "crisol", "cristal", "criterio", "cromo", "cronica", "crucero", "crujido",
    "cruz", "cuadro", "cuaderno", "cuarzo", "cubierta", "cuchara", "cuchillo", "cuello",
    "cuenca", "cuerda", "cuerno", "cuero", "cuerpo", "cueva", "cuidado", "culebra",
    "cultura", "cumbre", "cuna", "cupula", "curioso", "custodia", "dama", "danza",
    "dardo", "datil", "debate", "decada", "decision", "decoro", "dedal", "dedo",
    "defensa", "delfin", "delgado", "delicia", "demora", "dentro", "deporte", "deposito",
    "deriva", "derroche", "desafio", "descanso", "deseo", "desfile", "desierto", "despeje",
    "destino", "destello", "detalle", "diafragma", "dialogo", "diamante", "diario", "dibujo",
    "diccionario", "diente", "dieta", "difuso", "dinamo", "dinero", "diploma", "dique",
    "directo", "discurso", "diseno", "disparo", "distrito", "diurno", "division", "doble",
    "doctor", "doctrina", "dogma", "dolor", "domador", "domingo", "dominio", "donante",
    "dorado", "dormir", "dragon", "drenaje", "droga", "duende", "dueto", "dulce",
    "duo", "duplex", "duque", "durazno", "dureza", "eclipse", "eco", "ecologia",
    "economia", "edicion", "edificio", "editor", "educador", "efecto", "eficaz", "ego",
    "eje", "ejemplo", "ejercicio", "elixir", "elogio", "embalaje", "embudo", "emisor",
    "emocion", "empalme", "empeno", "empresa", "empuje", "enano", "encanto", "encargo",
    "enchufe", "encina", "energia", "enfoque", "enigma", "enlace", "ensayo", "entorno",
    "entrada", "envase", "envoltorio", "epica", "epoca", "equipaje", "equipo", "erizo",
    "ermita", "escala", "escalon", "escama", "escapada", "escape", "escarabajo", "escena",
    "esclavo", "escoba", "escotilla", "escudo", "escultura", "esfera", "esfuerzo", "esgrima",
    "eslabon", "esmalte", "esmeralda", "espacio", "espada", "espalda", "espejo", "espera",
    "espia", "espiga", "espina", "espiral", "esponja", "espuela", "espuma", "esquema",
    "esquina", "estacion", "estadio", "estampa", "estanque", "estante", "estatua", "estela",
    "estilo", "estimulo", "estribo", "estrofa", "estuche", "estudio", "etapa", "eterno",
    "etica", "evento", "evidencia", "exacto", "examen", "exceso", "exito", "experto",
    "fabrica", "faceta", "factor", "faena", "faisan", "faja", "falda", "fallo",
    "fango", "fantasma", "fardo", "farol", "fascinar", "fase", "fatal", "fauna",
    "favor", "faz", "febrero", "fecha", "felino", "feliz", "fenix", "feria",
    "feroz", "fertil", "festejo", "fibra", "ficcion", "figura", "fijador", "filamento",
    "filete", "filme", "filosofo", "filtro", "final", "finca", "firmeza", "flamenco",
    "flanco", "flauta", "flecha", "flete", "flexible", "floculo", "flor", "floresta",
    "flotador", "fluidez", "foco", "folleto", "fondo", "forja", "forma", "formula",
    "foro", "fortuna", "fosforo", "foto", "fraccion", "fragata", "frescura", "frijol",
    "frontera", "fuego", "fuente", "fuerte", "fuerza", "fuga", "fulgor", "humo",
    "gaceta", "gala", "galaxia", "galera", "galon", "gamba", "ganado", "gancho",
    "ganso", "garaje", "garant", "garbanzo", "garfio", "garganta", "garra", "garza",
    "gasolina", "gato", "gaviota", "gemelo", "gema", "genero", "genio", "gente",
    "geometra", "geranio", "germina", "gesto", "gigante", "gimnasia", "girasol", "giro",
    "glaciar", "globo", "gloria", "glosa", "golfo", "golpe", "goma", "gondola",
    "gorra", "gota", "grabado", "gracia", "gradual", "grafico", "gramo", "granada",
    "granito", "granja", "grapa", "grasa", "gratis", "gravedad", "greca", "gremio",
    "grillo", "grito", "gruta", "guante", "guarda", "guardian", "guerrero", "guia",
    "guion", "guirnalda", "guitarra", "gusano", "gusto", "habla", "halcon", "hallazgo",
    "hamaca", "harina", "haz", "hebilla", "hebra", "hechizo", "helado", "helecho",
    "helice", "heraldo", "herbolar", "herencia", "hermano", "herradura", "hervor", "hiedra",
    "hierba", "hierro", "hilera", "hilo", "himno", "hogar", "hoja", "holgura",
    "hombre", "hombro", "hondo", "hongo", "honor", "honra", "horizonte", "hormiga",
    "horno", "hospedaje", "hotel", "huella", "huerta", "hueso", "huesped", "humano",
    "humilde", "huracan", "icono", "idea", "ideario", "idilio", "idioma", "idolo",
    "iglesia", "ignicion", "iguana", "ilusion", "imagen", "iman", "impulso", "incendio",
    "incienso", "inclinacion", "indice", "infante", "infinito", "informe", "ingenio", "inicio",
    "inmenso", "invento", "invierno", "iris", "isla", "islote", "itinerario", "jabali",
    "jabon", "jade", "jaula", "jazmin", "jefe", "jinete", "jirafa", "jornada",
    "joya", "juego", "jueves", "jugador", "jugo", "juicio", "junco", "jungla",
    "junio", "junta", "jurar", "juzgado", "karma", "kayak", "kilo", "kimono",
    "kiosco", "koala", "laberinto", "labio", "labor", "lacre", "lado", "ladera",
    "ladrillo", "lagartija", "lago", "lagrima", "laguna", "laico", "lamina", "lampare",
    "lana", "lancha", "langosta", "lanza", "lapiz", "laurel", "lava", "lazo",
    "lealtad", "leche", "lector", "legado", "legumbre", "lejano", "lemur", "lengua",
    "lenteja", "leon", "leopardo", "letra", "leyenda", "libelula", "libro", "licor",
    "liebre", "lienzo", "liga", "lila", "limon", "linaje", "lince", "linda",
    "linea", "linterna", "lirio", "liso", "lista", "litro", "llama", "llave",
    "llegada", "lleno", "lluvia", "lobo", "locura", "logica", "logro", "loma",
    "lombriz", "lonja", "loro", "loto", "lucero", "lucha", "luciernaga", "lugar",
    "lujo", "lumbre", "luna", "lunes", "lupa", "luz", "maceta", "madera",
    "madre", "madriguera", "maestro", "magia", "magnolia", "mago", "maiz", "maletin",
    "malla", "mamifero", "manantial", "mando", "manga", "mango", "mano", "manso",
    "manta", "mantequilla", "manzana", "mapa", "maqueta", "maquina", "mar", "maraton",
    "marfil", "margen", "marina", "mariposa", "marmol", "martes", "martillo", "marzo",
    "mascara", "masivo", "materia", "matiz", "mayor", "mazo", "mecanismo", "medalla",
    "medida", "medio", "meditacion", "medusa", "mejilla", "melodia", "melon", "membrana",
    "memoria", "menhir", "mensaje", "mente", "menta", "mercado", "merengue", "merito",
    "meseta", "metal", "meteoro", "metodo", "metro", "mezcla", "miel", "miembro",
    "miga", "milagro", "milla", "mina", "mineral", "minuto", "mirada", "mision",
    "misterio", "mitad", "mochila", "modelo", "modesto", "molde", "molecula", "molino",
    "momento", "monarca", "moneda", "montana", "monte", "mora", "moral",
    "moreno", "morral", "mosaico", "motor", "muelle", "muestra", "mundo", "muralla",
    "musgo", "musica", "mutuo", "nacar", "nacion", "nadador", "naipe", "naranja",
    "nariz", "natal", "natura", "nave", "navio", "neblina", "nectar", "negocio",
    "nido", "niebla", "nieve", "noble", "noche", "nodriza", "nomada", "nombre",
    "nopal", "nordico", "norma", "norte", "noticia", "novela", "noviembre", "nube",
    "nucleo", "nudo", "nuera", "nueve", "nuez", "numero", "oasis", "objeto",
    "obrero", "ocelote", "ochenta", "octubre", "oculto", "ocupado", "oeste", "ofrenda",
    "oleaje", "olivo", "olmo", "onda", "onix", "opera", "opinion", "optimo",
    "oraculo", "orbita", "orden", "oreja", "orfebreria", "orgullo", "oriente", "origen",
    "orilla", "oro", "orquidea", "ortiga", "oruga", "ostra", "otono", "ovacion",
    "oveja", "oxigeno", "ozono", "pacifico", "pacto", "padre", "pagina", "paisaje",
    "palacio", "palanca", "paleta", "palma", "paloma", "panal", "pantera", "pantalla",
    "papel", "paquete", "paraiso", "parche", "pared", "parque", "partida", "pasaje",
    "paseo", "pasion", "pasta", "pastor", "patin", "patio", "patria", "pausa",
    "pavo", "peaje", "peine", "pelicano", "pelota", "pendulo", "pensamiento", "pepino",
    "perdiz", "perfil", "perfume", "perla", "perro", "pesca", "petalo", "piano",
    "picacho", "piedra", "piel", "pieza", "piloto", "pimienta", "pino", "pintor",
    "pira", "piramide", "pirata", "piscina", "pista", "pizarra", "placa", "planeta",
    "planta", "plata", "platano", "plato", "playa", "plaza", "pleamar", "pluma",
    "poblado", "poder", "poema", "poesia", "polvo", "pomelo", "poniente", "portal",
    "porvenir", "posada", "postre", "potro", "pozo", "prado", "precio", "premio",
    "prensa", "presa", "primavera", "primo", "prisma", "proeza", "profundo", "promesa",
    "pronto", "propio", "protector", "proverbio", "pueblo", "puente", "puerta", "puerto",
    "puesta", "pulgada", "pulpo", "pulso", "puma", "punta", "punto", "pupitre",
    "pureza", "purpura", "quebracho", "queda", "quijada", "quimica", "quince", "quinto",
    "radar", "radiante", "radon", "rafaga", "raiz", "rama", "rampa",
    "rana", "rancho", "rapido", "raqueta", "rasgo", "rastro", "raton", "rayo",
    "rebano", "rebote", "receta", "recinto", "recreo", "red", "reflejo", "reforma",
    "refugio", "regalo", "regazo", "regla", "reina", "reino", "reloj", "remanso",
    "remedio", "remo", "rendija", "renglon", "renuevo", "repaso", "resorte", "respeto",
    "respiro", "retablo", "reto", "retrato", "reunion", "revista", "rey", "ribera",
    "rico", "riego", "rienda", "rincon", "rio", "riqueza", "risueno", "ritmo",
    "rival", "roble", "robot", "roca", "rocio", "rodaja", "rodillo", "rodeo",
    "rombo", "romero", "ronda", "rosa", "rosal", "rotativo", "rubi", "rueda",
    "ruido", "rumbo", "rupestre", "ruta", "saber", "sabio", "sable", "sabot",
    "saeta", "sagaz", "salitre", "salmon", "salto", "salud", "salvia",
    "sandalia", "santo", "sauce", "secoya", "secreto", "sector", "sello", "selva",
    "semilla", "senda", "seno", "sentido", "separa", "serena", "serie", "serpiente",
    "servicio", "sesamo", "sideral", "siembra", "siesta", "siglo", "signo",
    "silbato", "silencio", "silla", "silueta", "silvestre", "simbolo", "sincero", "sirena",
    "sistema", "sitio", "soberano", "sobre", "socio", "solar", "soldado", "soledad",
    "solido", "solsticio", "sombra", "sombrero", "soneto", "sonido", "sonrisa", "soplo",
    "sorpresa", "sosiego", "suave", "subida", "suceso", "suelo", "sueno",
    "suerte", "sulfuro", "suma", "sumidero", "sur", "suspiro", "sustento", "tabique",
    "tabla", "tabor", "tacto", "taller", "tamiz", "tambor", "tanque", "tapa",
    "tapiz", "tarde", "tarjeta", "teclado", "techo", "tejedora", "tejido", "tela",
    "templo", "tenaz", "tenedor", "tenis", "teoria", "terreno", "tesoro", "testigo",
    "tiempo", "tienda", "tierra", "tigre", "timbre", "timon", "tinaja", "tintero",
    "tiovivo", "tipo", "tirador", "tiro", "tison", "titan", "tizne", "tobogan",
    "toldo", "tomate", "tono", "topacio", "toque", "torbellino", "tormenta", "torneo",
    "torre", "torrente", "tostada", "trabajo", "tractor", "tragaluz", "traje", "trampa",
    "trance", "tranquilo", "transito", "trapiche", "travesia", "trebol", "tregua", "tren",
    "tribuna", "tributo", "trigo", "trineo", "trono", "tropa", "trueno", "tulipan",
    "tumba", "tunel", "turbina", "turismo", "turquesa", "tutela", "ubicuo", "ullero",
    "ultimo", "umbral", "universo", "urbano", "urgencia", "urna", "usuario", "utensilio",
    "util", "utopia", "uva", "vagon", "valiente", "valle", "valor", "valvula",
    "vapor", "vaquero", "varon", "vaso", "vecino", "veleta", "velocidad", "vencedor",
    "venda", "veneno", "ventaja", "ventana", "verano", "verbo", "verdad", "verde",
    "vereda", "vertice", "vespertino", "vestido", "viaje", "viajero", "vibora", "vida",
    "vidrio", "viento", "vigilante", "vigor", "villa", "vinagre", "viola", "violonc",
    "viraje", "virtud", "visita", "vispera", "vista", "vital", "vitrina", "vivero",
    "volcan", "volumen", "vuelo", "vulcano", "yate", "yegua", "yelmo", "yema",
    "yeso", "zafiro", "zapato", "zarza", "zona", "zorro", "zueco", "zumbido"
)

# Garantizar lista única de palabras
UNIQUE_WORDS: tuple[str, ...] = tuple(dict.fromkeys(WORDS))
WORDLIST_SIZE: int = len(UNIQUE_WORDS)

